# Numpy Operations

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [6]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

In [7]:
arr1 + arr2

array([ 5,  7,  9, 11, 13, 15])

In [8]:
arr1 *2

array([ 2,  4,  6,  8, 10, 12])

### (arr*2) is aslo known as Scaler multiplication and (arr1 * arr2) is also known as vector multiplication

In [9]:
arr1 > 3

array([False, False, False,  True,  True,  True])

In [10]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3 .dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [11]:
arr3.dot(arr1)

ValueError: shapes (2,3) and (6,) not aligned: 3 (dim 1) != 6 (dim 0)

### Order is'nt fullfill in arr3.dot(arr1) because number of rows and columns are not same

In [12]:
arr4.max()

11

In [13]:
arr4.min()

6

In [14]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
arr4.min(axis = 0)

array([6, 7])

## Column-wise min number 

In [16]:
arr4.min(axis = 1)

array([ 6,  8, 10])

## Row-wise min number

In [17]:
arr4.sum()

51

In [18]:
arr4.sum(axis = 0)

array([24, 27])

In [19]:
arr4.mean()

8.5

In [20]:
arr4.mean(axis = 0)

array([8., 9.])

## .mean() function is use for to find the avarage

In [21]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

### the above .sin() function return us the sin value of each item in arr4.

In [25]:
arr4.std()

1.707825127659933

#### std() is a function provided by the NumPy library that calculates the standard deviation of an array or a set of values. Standard deviation is a measure of the amount of variation or dispersion of a set of values

In [22]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [24]:
np.sqrt(arr4)

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

In [27]:
np.square(arr4)

array([[ 36,  49],
       [ 64,  81],
       [100, 121]])

In [28]:
np.square(arr4)

array([[ 36,  49],
       [ 64,  81],
       [100, 121]])